import { IStocktakeItem } from "../types/stocktake";
export const mockRemainingStocktakeItems: IStocktakeItem[] = [
  {
    stocktakeItemId: 1,
    stockId: 101,
    name: 'Blue/White Neo Capsule',
    currentQuantity: 2000,
    priorQuantity: 2000,
    priorValue: 1000,
    countValue: 0,
    movement: 0,
    movementValue: 0,
    currentValue: 4000,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    stocktakeItemId: 2,
    stockId: 102,
    name: 'Orange/White Neo Capsule',
    currentQuantity: 1000,
    priorQuantity: 1000,
    priorValue: 500,
    countValue: 0,
    movement: 0,
    movementValue: 0,
    currentValue: 2000,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    stocktakeItemId: 3,
    stockId: 103,
    name: 'Red/White Neo Capsule',
    currentQuantity: 1500,
    priorQuantity: 1500,
    priorValue: 750,
    countValue: 0,
    movement: 0,
    movementValue: 0,
    currentValue: 3000,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    stocktakeItemId: 4,
    stockId: 104,
    name: 'Green/White Neo Capsule',
    currentQuantity: 800,
    priorQuantity: 800,
    priorValue: 400,
    countValue: 0,
    movement: 0,
    movementValue: 0,
    currentValue: 1600,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    stocktakeItemId: 5,
    stockId: 105,
    name: 'Purple/White Neo Capsule',
    currentQuantity: 1200,
    priorQuantity: 1200,
    priorValue: 600,
    countValue: 0,
    movement: 0,
    movementValue: 0,
    currentValue: 2400,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    stocktakeItemId: 6,
    stockId: 106,
    name: 'Yellow/White Neo Capsule',
    currentQuantity: 900,
    priorQuantity: 900,
    priorValue: 450,
    countValue: 0,
    movement: 0,
    movementValue: 0,
    currentValue: 1800,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
];

export const mockCountedStocktakeItems: IStocktakeItem[] = [
  {
    stocktakeItemId: 7,
    stockId: 107,
    name: 'Black/White Neo Capsule',
    currentQuantity: 700,
    priorQuantity: 700,
    priorValue: 350,
    countValue: 700,
    movement: 0,
    movementValue: 0,
    currentValue: 1400,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    stocktakeItemId: 8,
    stockId: 108,
    name: 'Pink/White Neo Capsule',
    currentQuantity: 600,
    priorQuantity: 600,
    priorValue: 300,
    countValue: 0,
    movement: 0,
    movementValue: 0,
    currentValue: 1200,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    stocktakeItemId: 9,
    stockId: 109,
    name: 'Cyan/White Neo Capsule',
    currentQuantity: 1100,
    priorQuantity: 1100,
    priorValue: 550,
    countValue: 0,
    movement: 0,
    movementValue: 0,
    currentValue: 2200,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    stocktakeItemId: 10,
    stockId: 110,
    name: 'Brown/White Neo Capsule',
    currentQuantity: 1000,
    priorQuantity: 1000,
    priorValue: 500,
    countValue: 0,
    movement: 0,
    movementValue: 0,
    currentValue: 2000,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    stocktakeItemId: 11,
    stockId: 111,
    name: 'Teal/White Neo Capsule',
    currentQuantity: 1300,
    priorQuantity: 1300,
    priorValue: 650,
    countValue: 0,
    movement: 0,
    movementValue: 0,
    currentValue: 2600,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
  {
    stocktakeItemId: 12,
    stockId: 112,
    name: 'Silver/White Neo Capsule',
    currentQuantity: 500,
    priorQuantity: 500,
    priorValue: 250,
    countValue: 0,
    movement: 0,
    movementValue: 0,
    currentValue: 1000,
    createdDate: new Date(),
    modifiedDate: new Date(),
  },
];